language: python

os:   linux
dist: trusty
sudo: required

python:
  - '3.6'

cache: pip

branches:
  only:
    - master

install:
  - .travis/install.sh

script:
  - .travis/build.sh

deploy:
  provider:     pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  local_dir:    'doc/html'
  on:
    branch: master
